load("@bazel_skylib//rules/directory:glob.bzl", "directory_glob")
load("@rules_go//go:def.bzl", "go_binary")
load(":transition.bzl", "transitioned_go_binary")

go_binary(
    name = "plain",
    srcs = ["hello.go"],
    cgo = True,
)

transitioned_go_binary(
    name = "transitioned",
    srcs = ["hello.go"],
    cgo = True,
)

directory_glob(
    name = "public_headers",
    srcs = ["**"],
    directory = "//sdk:headers",
)

directory_glob(
    name = "internal_headers",
    srcs = ["**"],
    directory = "//sdk:headers_directory",
)

genrule(
    name = "exec_transition",
    outs = ["exec_result.txt"],
    cmd = "$(execpath :transitioned) && echo ok > $@",
    tools = [":transitioned"],
)
